yuque:
  clientId: IvXExV0Mh9dopZHcO8kY
  clientSecret: mKMVIpJCc8LqoX86XhlmhiQ4kXc28Bk2OQRYTOrl
  authorizationGrantType: authorization_code
  redirectUri: http://localhost:8080/oauth2/authorized
  scope: repo:read,doc:read
  authorizationUri: https://www.yuque.com/oauth2/authorize
  tokenUri: https://www.yuque.com/oauth2/token
  userInfoUri: https://www.yuque.com/api/v2/user