yuque:
  clientId: ${YUQUE_CLIENT_ID}
  clientSecret: ${YUQUE_CLIENT_SECRET}
  authorizationGrantType: authorization_code
  redirectUri: ${YUQUE_REDIRECT_URI}
  scope: repo:read,doc:read
  authorizationUri: https://www.yuque.com/oauth2/authorize
  tokenUri: https://www.yuque.com/oauth2/token
