yuque:
  clientId: your client id
  clientSecret: your client secret
  authorizationGrantType: authorization_code
  redirectUri: http://localhost:8080/oauth2/authorized
  scope: repo:read,doc:read
  authorizationUri: https://www.yuque.com/oauth2/authorize
  tokenUri: https://www.yuque.com/oauth2/token
  userInfoUri: https://www.yuque.com/api/v2/user